language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libusb-1.0-0

install:
  - pip install "pip>=7.0.2" wheel
  - pip install --pre pyusb

script: "python setup.py test -s test.soft"
